MODULE MAX_PARAMETER_PP
  INTEGER, PARAMETER :: splnmax=5020
  INTEGER, PARAMETER :: nspln=5000
  INTEGER, PARAMETER :: lmaxx=5
  INTEGER, PARAMETER :: spmax=4
  INTEGER, PARAMETER :: atommax=100
  INTEGER, PARAMETER :: mpro=4
  INTEGER, PARAMETER :: maxngh=120
END MODULE MAX_PARAMETER_PP

