MODULE READpsp
CONTAINS

      SUBROUTINE psp
      USE system_data_types
      IMPLICIT NONE
        ALLOCATE(slatr_ex(sp_t),tnum(sp_t))
        !ALLOCATE(vr(splnmax,sp_t,lmaxx),rps(splnmax,sp_t,lmaxx))
      
      END SUBROUTINE psp






SUBROUTINE read_psp(pspfile,isp)
USE system_data_types
USE readstring
!USE 
IMPLICIT NONE

INTEGER :: ISP
INTEGER   IUNIT,ios
PARAMETER (IUNIT=20)
CHARACTER, INTENT(in) :: pspfile*(*)
INTEGER INDX_A,INDX_E,IT,I,L,LREAD
LOGICAL ERREAD

CHARACTER LINE*80, PATHOFPP*42
!DO IS=1,sp_t
TNUM(ISP)=.FALSE.
      OPEN(UNIT=IUNIT,FILE=trim(PATHOFINPUT)//'PSEUDOPOTENTIAL/'//pspfile,IOSTAT=ios)
      IF(ios.NE.0)THEN
        WRITE(*,*)"    Reading ",pspfile," is not successful"
        STOP
      ENDIF


!REWIND(IUNIT)
READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
CALL STRINGINDX(LINE,INDX_A,INDX_E)

IF(INDEX(LINE, LINE(INDX_A:INDX_E)) == 0)THEN
    WRITE(6,*)"&ATOM SECTION NOT FOUND"
ENDIF

READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
CALL STRINGINDX(LINE,INDX_A,INDX_E)
INDX_A=INDEX(LINE,'=')+1
CALL READ_I(LINE(INDX_A:LEN(LINE)),Z(ISP),ERREAD)
READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
CALL STRINGINDX(LINE,INDX_A,INDX_E)
INDX_A=INDEX(LINE,'=')+1
CALL READ_I(LINE(INDX_A:LEN(LINE)),ZV(ISP),ERREAD)

READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
CALL STRINGINDX(LINE,INDX_A,INDX_E)
INDX_A=INDEX(LINE,'=')+1
CALL READ_I(LINE(INDX_A:LEN(LINE)),XC_FUN(ISP),ERREAD)
INDX_A=INDEX(LINE,'.')-1!+INDX_E+1
CALL READ_R(LINE(INDX_A:LEN(LINE)),SLATR_EX(ISP),ERREAD)

READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
INDX_A=INDEX(LINE,'NUMERIC')
IF(INDX_A .NE. 0)TNUM(ISP)=.TRUE.

READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
IF(INDEX(LINE,'&INFO') .NE. 0) THEN
        IT=0
        DO I=1,60
        READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
        IF(INDEX(LINE,'&END').NE.0) GOTO 10
        IT=IT+1
        !INFOPP(IT,IS)=LINE(1:66)
        !WRITE(6,*)LINE
        ENDDO
   10 CONTINUE
ENDIF

READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
IF(INDEX(LINE,'&POTENTIAL') .NE. 0) THEN
READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
CALL STRINGINDX(LINE,INDX_A,INDX_E)
CALL READ_I(LINE(INDX_A:LEN(LINE)),MESHV(ISP),ERREAD)
       DO I=1,MESHV(ISP)
       READ(IUNIT,*) RR(I,ISP),(VR(I,ISP,L),L=1,LMAX(ISP))
       ENDDO
READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
IF(INDEX(LINE,'&END').EQ.0)WRITE(6,*)"SOMETHING WRONG no END"
ENDIF


READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
IF(INDEX(LINE,'&WAVEFUNCTION') .NE. 0) THEN
READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
CALL STRINGINDX(LINE,INDX_A,INDX_E)
CALL READ_I(LINE(INDX_A:LEN(LINE)),MESHW(ISP),ERREAD)
       DO I=1,MESHW(ISP)
       READ(IUNIT,*) RR(I,ISP),(RPS(I,ISP,L),L=1,LMAX(ISP))
       ENDDO
READ(IUNIT,END=20,ERR=20,FMT='(A)') LINE
IF(INDEX(LINE,'&END').EQ.0)WRITE(6,*)"SOMETHING WRONG no END"
IF(MESHW(ISP).NE.MESHV(ISP))WRITE(6,*)".......ERROR:INCOMPATIBLE MESHES..........",MESHW(ISP),MESHV(ISP)
         ENDIF
!ENDDO
20 CONTINUE
RETURN
END SUBROUTINE read_psp

END MODULE
